version: '3'

services:
  db:
    image: mongo
    ports:
      - "27017-27019:27017-27019"
  scraper:
    build: .
#    image: pedrocesarti/vimeo-scraper
    environment:
      - ID_START=335474674
      - ID_END=335474675
    links:
      - db
    depends_on:
      - db
