version: '3'

services:
  db:
    image: mongo
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - $PWD/datadir:/data/db
  scraper:
#    build: .
    image: pedrocesarti/vimeo-scraper
    environment:
      - ID_START=335000000
      - ID_END=339999999
    links:
      - db
    depends_on:
      - db
