version: '3'

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
      - "27018:27018"
      - "27019:27019"
  vimeo:
    build: .
    environment:
      - ID_START=335474674
      - ID_END=335474675
    links:
      - db
    depends_on:
      - db
